### ISSUE TITLE
Where did you get the GRch37 gencode list from?

### ISSUE THREAD

**Issue by jfrank94** [Geeketics/LocusZooms#16]
My team is using the list ({Gencode,UCSC}_GRCh37_Genes_UniqueList{2017,2021}.txt) currently as a part of our project as this was the best DB/list that we could find so far, but we would like to know the source of where it was procured? Did you use any special queries via SQL or used an interface to get this list as well? Also, we'd like to know why the list is smaller than normal? Thank you in advance.

**Comment by Geeketics** [comment]
Kia ora,

Details of where source data for genelists & how they were cleaned can be found in the `https://github.com/Geeketics/LocusZooms/blob/master/making_genelists/` directory.

Please, don't forget to cite this repo (https://doi.org/10.5281/zenodo.5154379) in any publications that come from using these files. :)
