### ISSUE TITLE
Error in if (length > 5000) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by 013345Jennifer** [Geeketics/LocusZooms#18]
Hi there, 

I am having the following issue when trying to use the example data in the locus.zoom function:

"Error in if (length > 5000) { : missing value where TRUE/FALSE needed
In addition: Warning message:
In locus.zoom(data = Example.assoc.linear, region = c(16, 53340000,  :
  NAs introduced by coercion"

My apologies if this is an issue I am introducing, but I was wondering if anyone had encountered anything similar or had any ideas about the error.  I have used both the example data and my own data and I get the same error.
Thank you.

**Comment by 013345Jennifer** [comment]
Solved with help from the creator. 
In my own data, some of the chromosomes in the genes file were still alphanumeric, once  I ensured that all animal chromosomes were changed to numeric, it worked perfectly.
When the  "Gencode_GRCh37_Genes_UniqueList2021.txt" file is used as in the readme, the example data runs perfectly,  I had been using UCSC_GRCh37_Genes_UniqueList2021.txt.

**Comment by Geeketics** [comment]
#
