### ISSUE TITLE
GRch38 gencode list any time soon?

### ISSUE THREAD

**Issue by catheriz** [Geeketics/LocusZooms#22]
Hi,
I am trying to use this great tool to create locuszoom plots. Will you guys provide GRch38 gencode list any soon as an update of the package?

Thank you

**Comment by Geeketics** [comment]
Kia ora Catheriz,

I am not actively working with /updating this code anymore, but the code I used to get the gene lists is in the repo, so you could download a GRch38 gene list and work through the steps I went through to make your own gene list.

If you are only plotting certain regions of the genome you wouldn't have to make a gene list for the whole genome either, only the area(s) that you are plotting.

Kia pai tō rā,
Tanya
