### ISSUE TITLE
convert gff3 to your gene format

### ISSUE THREAD

**Issue by shaoxiong2588** [Geeketics/LocusZooms#23]

**Comment by shaoxiong2588** [comment]
how to convert gff3 to your gene format ""Gencode_GRCh37_Genes_UniqueList2021.txt"

**Comment by Geeketics** [comment]
Hi,
There is [code detailing how I converted the original files](https://github.com/Geeketics/LocusZooms/blob/master/making_genelists/gencode_GeneList2021.R) I had to the gene format files that the code uses. I started with "gtf" format files, so you would have to compare the contents of "gtf" to "gff" files to see if you're missing any info. The minimum your gene file needs for the code to run is five columns, "Gene", "Chrom", "Start", "End", and "Coding".
